version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'
  base-directory: build
