AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Smart Photo Album
Resources:
  searchphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos-2
      Description: "Lambda function for searching photos CD demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::614741084428:role/service-role/search-photos-role-ugytxk6x"
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      Environment:
        Variables:
          REGION: us-east-1

  indexphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos-2
      Description: "Lambda function for indexing photos CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::614741084428:role/service-role/index-photos-role-lms5y5p7"
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
      Environment:
        Variables:
          REGION: us-east-1

  Bucket1:
    Type: 'AWS::S3::Bucket'
